### ISSUE TITLE
GET to /youtube returns empty array

### ISSUE THREAD

**Issue by 0xZakk** [jwilld/artist-concerts-api#3]
When I make a GET request to `/youtube`, I get an empty array. I get the following error when trying to seed in youtube links:

```
node:8237) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/Users/zakk/ga/wdi/grading/02-project/jerry/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/zakk/ga/wdi/grading/02-project/jerry/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/zakk/ga/wdi/grading/02-project/jerry/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by jwilld** [comment]
youtube now shows the links
